### ISSUE TITLE
Map ID string not found - not an MRC file, or file is corrupt

### ISSUE THREAD

**Issue by SanatMoharir** [PrincetonUniversity/APPLEpicker-python#15] opened 2019-01-22 11:55 UTC
Hello,
Whenever I am passing my .MRC file , its giving me an error.  Can you please tell me the solution. 

converting 1 mrc files..
Processing Jul21_18_01_08.mrc..
C:\Users\Sanat Mohrir\AppData\Local\conda\conda\envs\tfg\lib\site-packages\mrcfile\mrcinterpreter.py:203: RuntimeWarning: Map ID string not found - not an MRC file, or file is corrupt
  warnings.warn(msg, RuntimeWarning)
C:\Users\Sanat Mohrir\Documents\GitHub\APPLEpicker-python\apple\helper.py:279: RuntimeWarning: invalid value encountered in sqrt
  std_all = np.sqrt(var_all)

**Comment by janden** [comment] 2019-01-22 12:31
It could be that there's a slight negative value caused by the subtraction on the previous line of `helper.py`. Because of rounding errors, it might be something like `-1e16`, which makes `np.sqrt` complain. Putting a `max(0, var_all)` should fix that.

**Comment by SanatMoharir** [comment] 2019-01-22 13:19
can you please let us know which file we need to change.

**Comment by SanatMoharir** [comment] 2019-01-22 14:00
Hello @janden, I have added max(0, var_all) but this error is erupting. Please help me. Thank you in advance !!!!
converting 1 mrc files..
Processing micrograph.mrc..
Traceback (most recent call last):
  File "run.py", line 49, in <module>
    apple.pick_particles()
  File "C:\Users\Sanat Mohrir\Documents\GitHub\APPLEpicker-python\apple\apple.py", line 170, in pick_particles
    Apple.process_micrograph(data, filenames[0])
  File "C:\Users\Sanat Mohrir\Documents\GitHub\APPLEpicker-python\apple\apple.py", line 223, in process_micrograph
    score = picker.query_score(micro_img)  # compute score using normalized cross-correlations
  File "C:\Users\Sanat Mohrir\Documents\GitHub\APPLEpicker-python\apple\picking.py", line 94, in query_score
    self.container_size)
  File "C:\Users\Sanat Mohrir\Documents\GitHub\APPLEpicker-python\apple\helper.py", line 140, in extract_references
    mean_all, std_all = cls.moments(img, query_size)
  File "C:\Users\Sanat Mohrir\Documents\GitHub\APPLEpicker-python\apple\helper.py", line 279, in moments
    std_all = max(var_all)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by janden** [comment] 2019-01-22 14:06
Sorry I put down the wrong thing. You'll want to put
```
std_all = np.sqrt(np.maximum(0, var_all))
```
Let me know if this helps.

**Comment by SanatMoharir** [comment] 2019-01-23 10:22
@janden Thank You, sir, It did resolve my issue. But now I am getting some other issue so I am going to create a separate issue for it. Thank you again!

**Comment by janden** [comment] 2019-01-23 17:57
We should fix this in the code before closing the issue.

**Closed** 2019-01-23 20:00 UTC
